### ISSUE TITLE
I click the .exe and nothing happens

### ISSUE THREAD

**Issue by RonaldBolado** [jpablodrexler/jp-photo-manager#164]
Any idea what could be happening? I can't follow these instructions because I can't find the files.

Open the solution file JPPhotoManager/JPPhotoManager.sln and run the JPPhotoManager/JPPhotoManager/JPPhotoManager.UI.csproj project.

**Comment by jpablodrexler** [comment]
Hi, are you clicking the .exe file packaged in a release zip?
The JPPhotoManager/JPPhotoManager.sln and JPPhotoManager/JPPhotoManager/JPPhotoManager.UI.csproj are part of the source code, that you can get by cloning the repository.
